In [5]:
using ReverseDiffSource


In [42]:
# Defining Hock-Schittkowksi problems 6-9


# Prob 6, dimension = 2, x* = [1,1]
f6(x) = (1 - x[1])^2
c6(x) = 10*(x[2] - x[1]^2)
x6_0 = [-1.2, 1]

# Prob 7, dimension = 2, x* = [0,sqrt(3)]
f7(x) = log(1 + x[1]^2) - x[2]
c7(x) = (1 + x[1]^2)^2 + x[2]^2 - 4
x7_0 = [2,2]

# Prob 8, dimension = 2, x* = [a,9/a], [-a,-9/a], a = sqrt( ( 25 +- sqrt(301) )/2 )
f8(x) = -1*x[1]^0
c81(x) = x[1]^2 + x[2]^2 - 25
c82(x) = x[1]*x[2] - 9
x8_0 = [2,1]
a = sqrt( ( 25 - sqrt(301) )/2 );
x8star1 = [a,9/a]
x8star2 = [-a,-9/a]
a = sqrt( ( 25 + sqrt(301) )/2 );
x8star3 = [a,9/a]
x8star4 = [-a,-9/a]

# Prob 9, dimension = 2, x* = [12k - 3, 16k - 4] for integer k
f9(x) = sin(pi*x[1]/12)*cos(pi*x[2]/16)
c9(x) = 4*x[1] - 3*x[2]
x9_0 = [0,0]

2-element Array{Int64,1}:
 0
 0

In [47]:
# DIDN'T WORK THIS WAY wrt ReverseDiffSource

# L(x,y,rho) = f(x) - y'*c(x) + (rho/2)*c(x)'*c(x)
# L6(x,y,rho) = (1 - x[1])^2 - y[1]*10*(x[2] - x[1]^2) + (rho/2)*(10*(x[2] - x[1]^2))^2
global y
global rho
y = 1
rho = 1

L7(x) = log(1 + x[1]^2) - x[2] - y[1]*((1 + x[1]^2)^2 + x[2]^2 - 4) + (rho/2)*((1 + x[1]^2)^2 + x[2]^2 - 4)^2
# L8(x,y,rho) = -1 - y[1]*(x[1]^2 + x[2]^2 - 25) - y[2]*(x[1]*x[2] - 9) + (rho/2)*((x[1]^2 + x[2]^2 - 25)^2 + (x[1]*x[2] - 9)^2)
# L9(x,y,rho) = sin(pi*x[1]/12)*cos(pi*x[2]/16) - y[1]*(4*x[1] - 3*x[2]) + (rho/2)*(4*x[1] - 3*x[2])^2

# diff_f6 = rdiff( f6, (ones(2),), order = 2)
diff_f7 = rdiff( f7, (ones(2),), order = 2)
# diff_f8 = rdiff( f8, (ones(0),), order = 2)
# diff_f9 = rdiff( f9, (ones(2),), order = 2)

# diff_c6 = rdiff( c6, (ones(2),), order = 2)
diff_c7 = rdiff( c7, (ones(2),), order = 2)
#diff_c81 = rdiff( c81, (ones(2),), order = 2)
# diff_c82 = rdiff( c82, (ones(2),), order = 2)
# diff_c9 = rdiff( c9, (ones(2),), order = 2)

# diff_L6 = rdiff( L6, (ones(4),), order = 2)
diff_L7 = rdiff( L7, (ones(2),), order = 2)
# diff_L8 = rdiff( L8, (ones(5),), order = 2)
# diff_L9 = rdiff( L9, (ones(4),), order = 2)

L7(x,y,rho) = log(1 + x[1]^2) - x[2] - y[1]*((1 + x[1]^2)^2 + x[2]^2 - 4) + (rho/2)*((1 + x[1]^2)^2 + x[2]^2 - 4)^2

diff_L7 = rdiff( L7, (ones(4),), order = 2)


(anonymous function)

In [49]:
### Our fix for forcing ReverseDiffSource to work

L6(x) = (1 - x[1])^2 - x[3]*10*(x[2] - x[1]^2) + (x[4]/2)*(10*(x[2] - x[1]^2))^2
L7(x) = log(1 + x[1]^2) - x[2] - x[3]*((1 + x[1]^2)^2 + x[2]^2 - 4) + (x[4]/2)*((1 + x[1]^2)^2 + x[2]^2 - 4)^2
L8(x) = -1 - x[3]*(x[1]^2 + x[2]^2 - 25) - x[4]*(x[1]*x[2] - 9) + (x[5]/2)*((x[1]^2 + x[2]^2 - 25)^2 + (x[1]*x[2] - 9)^2)
L9(x) = sin(pi*x[1]/12)*cos(π*x[2]/16) - x[3]*(4*x[1] - 3*x[2]) + (x[4]/2)*(4*x[1] - 3*x[2])^2


diff_f6 = rdiff( f6, (ones(2),), order = 2)
diff_f7 = rdiff( f7, (ones(2),), order = 2)
diff_f8 = rdiff( f8, (ones(1),), order = 2)
diff_f9 = rdiff( f9, (ones(2),), order = 2)

diff_c6 = rdiff( c6, (ones(2),), order = 2)
diff_c7 = rdiff( c7, (ones(2),), order = 2)
diff_c81 = rdiff( c81, (ones(2),), order = 2)
diff_c82 = rdiff( c82, (ones(2),), order = 2)
diff_c9 = rdiff( c9, (ones(2),), order = 2)


diff_L6 = rdiff( L6, (ones(4),), order = 2)
diff_L7 = rdiff( L7, (ones(4),), order = 2)
diff_L8 = rdiff( L8, (ones(5),), order = 2)
diff_L9 = rdiff( L9, (ones(4),), order = 2)

diff_L6([0,0,0,0])
function Ltemp(diff_L,x,y,rho,n)
    tmp=diff_L([x,y,rho])
    return (tmp[1], tmp[2][1:n],tmp[3][1:n,1:n])
end

Ltemp (generic function with 1 method)

In [9]:
function warmup(warmUp, obj, x, its, fvals, gNormVals)
    for i = 1:warmUp
        (f,g,H) = obj(x);
        (sigma, V) = eig(H)
        L = maximum(sigma)
        x = x - (1/L)*g

        its = its + 1;
        fvals = [fvals; f];
        gNormVals = [gNormVals; norm(g,2)];
    end
    return (x,its,fvals,gNormVals)
end

warmup (generic function with 1 method)

In [10]:
function newtstep1(obj,x,its,fvals,gNormVals)
    (f,g,H) = obj(x);
        
    #modify H if not pos def
    E = eigfact(H);
    V = E[:vectors];
    lambda = diagm(max(abs(E[:values]),1e-2));
    d = -V*inv(lambda)*transpose(V)*g;
        
    #backtracking linesearch
    alpha = 1;
    mu = 10^-2.0;
    (newf,newg,newH) = obj(x+alpha*d);
    while newf > f + (alpha*mu)*(dot(g,d))
        (newf, newg, newH) = obj(x + alpha*d);
        alpha = alpha/2;
    end

    x = x+alpha*d;

    its = its + 1;
    fvals = [fvals; f];
    gNormVals= [gNormVals; norm(g,2)];
    return(x,g,its,fvals,gNormVals);
end


newtstep1 (generic function with 1 method)

In [11]:
function newtstep2(obj,x,its,fvals,gNormVals)
    (f,g,H) = obj(x);
        
    #modify H if not pos def
    E = eigfact(H);
    V = E[:vectors];
    lambda = diagm(max(E[:values],1e-2));
    d = -V*inv(lambda)*transpose(V)*g;
        
    #backtracking linesearch
    alpha = 1;
    mu = 10^-2.0;
    (newf,newg,newH) = obj(x+alpha*d);
    while newf > f + (alpha*mu)*(dot(g,d))
        (newf, newg, newH) = obj(x + alpha*d);
        alpha = alpha/2;
    end

    x = x+alpha*d;

    its = its + 1;
    fvals = [fvals; f];
    gNormVals= [gNormVals; norm(g,2)];
    return(x,g,its,fvals,gNormVals);
end


newtstep2 (generic function with 1 method)

In [12]:
function BFGSstep(obj,x,B,its,fvals,gNormVals)
    (f,g,H) = obj(x);
    d = -B\g;
        
    
    #backtracking linesearch with Wolfe condition
    alpha = 1;
    mu = 10^-2.0;
    nu = 0.8;
    oldx = x;
    (oldf,oldg,oldH) = obj(x);
    (newf,newg,newH) = obj(x+alpha*d);
    alphaDir = 0;
    while newf > f + (alpha*mu)*(dot(g,d))
        (newf, newg, newH) = obj(x + alpha*d);
        alpha = alpha/2;
    end

    x = x+alpha*d;
    (f,g,H) = obj(x);
    q = alpha*B*d;
    y = g - oldg;
    s = x - oldx;
    
    B = B - (1/(transpose(q)*s)[1])*(q*transpose(q)) + (1/(transpose(y)*s)[1])*(y*transpose(y));
    
    its = its + 1;
    fvals = [fvals; f];
    gNormVals= [gNormVals; norm(g,2)];
    return(x,B,g,its,fvals,gNormVals);
end

BFGSstep (generic function with 1 method)

In [13]:
function Or(boolArray)
    for i=1:size(boolArray,1)
        if boolArray[i] == true
            return (true, i)
        end
    end
    return (false,size(boolArray,1))
end

Or (generic function with 1 method)

In [14]:
function newtmin(obj, x0, maxIts, optTol, warmUp, whileSwitch, randPerts,newtVers)
    fvals = [];
    gNormVals=[];
    (f0,g0,H0) = obj(x0);
    x = x0;
    (f,g,H) = obj(x);
    its = 0;
    B = eye(size(x0,1));
    

    if warmUp > 0
        (x,its,fvals,gNormVals) = warmup(warmUp,obj,x,its,fvals,gNormVals);
    end
    
    while (norm(g,2) > optTol*whileSwitch*norm(g0,2) && norm(g,2) > 1e-8 && its < maxIts)
        if newtVers == 1
            (x,g,its,fvals,gNormVals) = newtstep1(obj,x,its,fvals,gNormVals);
        end
        if newtVers == 2
            (x,g,its,fvals,gNormVals) = newtstep2(obj,x,its,fvals,gNormVals);
        end
        if newtVers == 3
            (x,B,g,its,fvals,gNormVals) = BFGSstep(obj,x,B,its,fvals,gNormVals)
        end
    end 
    
    if norm(g,2) < optTol*whileSwitch*norm(g0,2) || norm(g,2) < 1e-8
#        println("Method computed optimal x: ", x)
#        println("\nIterations: ", its)
#        println("\nObjective: ", f)
#        println("\nInitial gradient norm: ", norm(g0,2))
#        println("\nGradient norm: ", norm(g,2))
        return (x, its, fvals, gNormVals)
    else
        perts = 0;
        while perts < randPerts
            E = eigfact(H);
            lambda = E[:values];
            V = E[:vectors];
            if Or(lambda.<0)[1]
                perts = perts + 1
                x = x + optTol*V[Or(lambda.<0)[2]];         #use small perturbation in decreasing eigenvector direction
                while (norm(g,2) > optTol*whileSwitch*norm(g0,2) && norm(g,2) > 1e-8 && its < (perts + 1)*maxIts)
                    (x,g,its,fvals,gNormVals) = newtstep1(x,its,fvals,gNormVals);
                end 
            end
            if norm(g,2) < optTol*whileSwitch*norm(g0,2) || norm(g,2) < 1e-8
#                println("Method computed optimal x: ", x)
#                println("\nIterations: ", its)
#                println("\nObjective: ", f)
#                println("\nInitial gradient norm: ", norm(g0,2))
#                println("\nGradient norm: ", norm(g,2))
                return (x, its, fvals, gNormVals)
            end
        end
#        println("Method timed out on maxIts: ", its)
#        println("\nx: ", x)
#        println("\nObjective: ", f)
#        println("\nInitial gradient norm: ", norm(g0,2))
#        println("\nGradient norm: ", norm(g,2))
    end
    return (x, its, fvals, gNormVals);
end

newtmin (generic function with 1 method)

In [30]:
# Iterative Augmented Lagrangian Method
# L(x,y,rho) = f(x) - y'*c(x) + (rho/2)*c(x)'*c(x)

function augLag(LagOracle,fcnOracle,constraintOracle,LtempOracle,x0,maxIts)
    rho = 1
    y = 1
    f = fcnOracle
    c = constraintOracle
    x = x0
    n = size(x)[1]
    L(x) = LtempOracle(LagOracle,x,y,rho,n)
    k = 1
    eta = 1/k
    rho = 1e-2
    cTol = 1e-4
    gTol = 1e-4           # newtmin(obj, x0, maxIts, optTol, warmUp, whileSwitch, randPerts,newtVers)
    y = -rho*c(x)[1]
    (x, its, fvals, gNormVals) = newtmin(L, x, 1000, 1e-3, 10, 1, 0, 3)
    println("found initial x")
    y = y - rho*c(x)[1]
    
    while ( (norm(c(x)[1]) > cTol) || (norm(f(x)[2] - c(x)[2]*y) > gTol) ) && (k < maxIts)
        if (norm(c(x)[1]) < eta)
            y = y - rho*c(x)[1]
            println("norm of c(x) was small enough")
        else
            rho = 10*rho
            println("norm of c(x) was too big, make rho go big now")
        end
        (x, its, fvals, gNormVals) = newtmin(L, x, 1000, 1e-3, 0, 1, 0, 3)
        k = k + 1
        eta = 1/k
        println("passed iteration ",k," with x =",x,", c(x) = ",c(x)[1])
    end
    
    return (x, k)
end

augLag (generic function with 1 method)

In [16]:
(xstar,k) = augLag(diff_L6, diff_f6, diff_c6, Ltemp, x6_0, 10)

found initial x
norm of c(x) was too big, make rho go big now
passed iteration 2 with x =[1.0017416720674914,1.0030940067314225], c(x) = -0.003923708251509783
norm of c(x) was small enough
passed iteration 3 with x =[0.9999999438941932,1.0001597518647922], c(x) = 0.0015986407640267153
norm of c(x) was small enough
passed iteration 4 with x =[0.9999999817105364,0.9999998129448356], c(x) = -1.504762374704427e-6


([1.0,1.0],4)

In [36]:
(xstar,k) = augLag(diff_L7, diff_f7, diff_c7, Ltemp, x7_0, 10)

found initial x
norm of c(x) was small enough
passed iteration 2 with x =[0.0,1.8544562505697986], c(x) = 0.4390079852773958
norm of c(x) was small enough
passed iteration 3 with x =[0.0,1.830613044650613], c(x) = 0.3511441192449869
norm of c(x) was too big, make rho go big now
passed iteration 4 with x =[0.0,1.769234960852448], c(x) = 0.13019234670256274
norm of c(x) was small enough
passed iteration 5 with x =[0.0,1.743815343628002], c(x) = 0.04089195267244605
norm of c(x) was small enough
passed iteration 6 with x =[0.0,1.735842817363123], c(x) = 0.013150286591145033
norm of c(x) was small enough
passed iteration 7 with x =[0.0,1.7332797881786248], c(x) = 0.004258824108537951
norm of c(x) was small enough
passed iteration 8 with x =[0.0,1.7324494253215657], c(x) = 0.0013810112970231714
norm of c(x) was small enough
passed iteration 9 with x =[0.0,1.7321805444846723], c(x) = 0.00044943869121638613
norm of c(x) was small enough
passed iteration 10 with x =[0.0,1.7320929772168083], c(x

([0.0,1.73209],10)

In [52]:
(xstar, k) = augLag(diff_L8, diff_f8, diff_c81, Ltemp, x8_0, 10)

LoadError: BoundsError()
while loading In[52], in expression starting on line 1

In [23]:
z = 1
y = 1

1

In [21]:
f15(x) = x[1]^2*y[1]^2*z[1]^2

f15 (generic function with 1 method)

In [24]:
diff_ftest = rdiff( f15, (ones(1),), order = 2)

(anonymous function)

In [25]:
f15(x,y,z) = x[1]^2*y[1]^2*z[1]^2

f15 (generic function with 2 methods)

In [26]:
diff_ftest = rdiff( f15, (ones(3),), order = 2)

(anonymous function)

In [27]:
z = 1

1

In [28]:
diff_ftest([4])

(16,[8.0],
1x1 Array{Float64,2}:
 2.0)

In [35]:
size(x6_0)[1]

2

In [30]:
diff_ftest([4])

(64,[32.0],
1x1 Array{Float64,2}:
 8.0)

In [26]:
f12(x) = x[1]^2
f13(x) = x[1]

f13 (generic function with 1 method)

In [27]:
f14(f12,f13,x) = f12(x) + f13(x)

f14 (generic function with 1 method)

In [28]:
f14(f12,f13,2)

6

In [ ]:
diff_Q = (.5*x'*Q*x+q'*x, Q*x+q, Q)
diff_const = (A*x-b, A', 0)
diff_QLag = ()


In [ ]:
A = rand(2,5)
b = rand(2,1)
Q = rand(5,5)
Q = Q + Q'
q = rand(5,1)

In [ ]:
xstar = [Q -A'; A zeros(2,2)]\[-q; b]
xstar = xstar[1:5,1]

In [ ]:
(xstar, k) = augLag(LagOracle,fcnOracle,constraintOracle,x0,maxIts)

In [43]:
x = (ones(2),)

([1.0,1.0],)